### ISSUE TITLE
RadiusOfGyration cannot work properly if weighByMass is True

### ISSUE THREAD

**Issue by smliu1997** [RedesignScience/cvpack#30]
Hi, 

So I use the following code to define Rg

```
# set umbrella bias
n_atoms = top.getNumAtoms()
rg = cvpack.RadiusOfGyration(list(range(n_atoms)), pbc=protein.use_pbc, weighByMass=True)
rg_bias = mm.CustomCVForce(f'0.5*{args.umbrella_kappa}*(rg-{args.umbrella_center})^2')
rg_bias.addCollectiveVariable('rg', rg)
rg_bias.setForceGroup(4)
protein.system.addForce(rg_bias)
```

And got such error
```
Traceback (most recent call last):
  File "/home/gridsan/sliu/Projects/run-cg-simulations/HPS-Urry-umbrella-simulations/run_hps_urry_umbrella_rg.py", line 63, in <module>
    rg = cvpack.RadiusOfGyration(list(range(n_atoms)), pbc=protein.use_pbc, weighByMass=True)
  File "/home/gridsan/sliu/.conda/envs/torch_cuda_env/lib/python3.9/site-packages/cvpack/radius_of_gyration.py", line 80, in __init__
    self.addGroup(group, None if weighByMass else [1] * num_atoms)
  File "/home/gridsan/sliu/.conda/envs/torch_cuda_env/lib/python3.9/site-packages/openmm/openmm.py", line 6591, in addGroup
    return _openmm.CustomCentroidBondForce_addGroup(self, *args)
TypeError: 'NoneType' object is not iterable
Additional information:
Wrong number or type of arguments for overloaded function 'CustomCentroidBondForce_addGroup'.
  Possible C/C++ prototypes are:
    OpenMM::CustomCentroidBondForce::addGroup(std::vector< int,std::allocator< int > > const &,std::vector< double,std::allocator< double > > const &)
    OpenMM::CustomCentroidBondForce::addGroup(std::vector< int,std::allocator< int > > const &)
```

If weighByMass is False then the code can run properly. I guess the problem is related to 
```
self.addGroup(group, None if weighByMass else [1] * num_atoms)
```
where the atom mass is not set properly when weighByMass is True?

**Comment by craabreu** [comment]
Thanks for pointing this out. PR #31 fixed this use. The documentation has been updated to improve clarity.
